### ISSUE TITLE
Doesn't run in IDA 6.8

### ISSUE THREAD

**Issue by pgiblock** [wjp/idados#4]
This idados remote debugger plugin fails to initialize on IDA 6.8. An error is displayed upon selecting the debugger from the debugger dropdown on the toolbar, or through the "Debugger -> Switch Debugger ..." menu option. IDA immediately exits upon dismissing the error dialog. The message is:

    " Wrong DBG_RESMOD_STEP_... bits "

I imagine this is due to the plugin not initializing some value. Most likely `debugger_t::resume_modes` is not filled. I'm still struggling to determine how this plugin initializes the debugger structure and how it assigns it to the global `dbg` variable.

**Comment by wjp** [comment]
I just committed cfceb1c12eb252775e0a23a3b473a94d69061654. Does that help?

**Comment by pgiblock** [comment]
This was actually easy to "fix", see https://github.com/pgiblock/idados/commit/9842c7813659f4b912660c1514b53733759e1b81

**Comment by pgiblock** [comment]
haha. that commit you made is probably more appropriate than my commit. I'll check it out
